#!/bin/bash

server="http://localhost:8080"

created=$(mktemp)
downloaded=$(mktemp)
trap 'rm -rf ${created} ${downloaded}' EXIT

cat << EOF > ${created}
${@:-"SOMETHING"}
EOF

id=$(curl --silent -F "file=@${created}" -F "blah=foo" \
    ${server}/upload | sed -r 's/[{}]//g;s/.*:"([^"]*)"$/\1/')
echo "ID: ${id}"

curl --silent ${server}/info/${id}
echo ""

curl --silent -o ${downloaded} ${server}/file/${id}

cat ${downloaded}
diff -s ${created} ${downloaded}
