version: '2'
services:
    mongodb:
        image: mongo:latest
        ports:
            - 27017:27017
        networks:
            - default
    finra:
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - 8080:8080
        depends_on:
            - mongodb
        networks:
            - default
        logging:
            driver: json-file
