#!/bin/bash

version=$(awk -F= '$1 ~ /api.version/ { print $2 }' application.properties)
server="http://localhost:8080/v${version}"

tmpFiles=()
tmp() {
    f=$(mktemp)
    tmpFiles+=(${f})
    echo ${f}
}
trap 'rm -rf ${tmpFiles[@]}' EXIT

declare -A uploadedFiles
declare -A uploadedFilesParams

genMetadata() {
    local ficha=$1
    local extra_metadata=$2
    stat --printf="user=%U\npermissions=%a\ncreated=%Y\n${extra_metadata}" ${ficha}
}

getMetadataFromJSON() {
    # TODO
    :
}

uploadFile() {
    local created=$1
    local extra_metadata=$2

    ## Generate random data for the file
    cat << EOF > ${created}
    $(strings /dev/urandom | grep -o '[[:alnum:]]' | head -n $((RANDOM%100)) | tr -d '\n')
EOF

    ## Create some parameters
    params=()
    for param in $(genMetadata ${created} ${extra_metadata}); do
        params+=("-F" "${param}")
    done

    id=$(curl --silent \
            -F "file=@${created}" \
            "${params[@]}" \
        ${server}/upload | sed -r 's/[{}]//g;s/.*:"([^"]*)"$/\1/')

    echo ${id}
}

verifyFile() {
    local id=$1

    # TODO: Actually use this
    curl --silent ${server}/metadata/${id}
    echo ""

    downloaded=$(tmp)
    curl --silent -o ${downloaded} ${server}/file/${id}

    diff ${uploadedFiles[${id}]} ${downloaded}
}

search_metadata="extra=foo"

## Generate a random number of files between 1 and 10
for i in $(seq 1 $((RANDOM%11))); do
    created=$(tmp)

    # Add extra metadata for searching
    (( $((RANDOM%3)) == 0 )) && extra_metadata=${search_metadata}
    id=$(uploadFile ${created} ${extra_metadata})
    unset extra_metadata

    uploadedFiles[${id}]=${created}
done

## Verify each file created
for id in "${!uploadedFiles[@]}"; do
    verifyFile ${id} || exit 1
done

echo "Testing search"
curl --silent \
     -F "extra=foo" \
     ${server}/search
